### ISSUE TITLE
Probably not your fault.. any idea why I am getting "Page Unavailable" with every auth request?

### ISSUE THREAD

**Issue by ccwasden** [maximbilan/ios_quizlet_client#1]
So, I have followed your directions in the Readme.. but after seeing this: 

![screen shot 2015-02-17 at 7 50 58 pm](https://cloud.githubusercontent.com/assets/844712/6241653/517b0738-b6de-11e4-980a-8259be9ffca2.png)

I always see this after confirming and Quizlet never redirects back to my app.....

![screen shot 2015-02-17 at 7 49 51 pm](https://cloud.githubusercontent.com/assets/844712/6241648/3562edc2-b6de-11e4-94a6-ddbd186fdafd.png)

Here is what my code looks like

```
 [[Quizlet sharedQuizlet] startWithClientID:@"________"
                                 withSecretKey:@"________"
                               withRedirectURI:@"wasdesign.us://after_oauth"];
```

And here is what my redirect uri is in the quizlet dashboard:

![image](https://cloud.githubusercontent.com/assets/844712/6241673/879697a6-b6de-11e4-872d-cc01e3218f59.png)

**Comment by maximbilan** [comment]
I just seen the example, and all is ok.
Maybe it's some problem with your quizlet keys and redirect URI.

I see in my test quizlet account:
![screen shot 2015-02-18 at 10 28 21](https://cloud.githubusercontent.com/assets/3020089/6244233/23813f98-b759-11e4-94a3-7d72df06719a.png)

Please, try to add 'after_oauth' to your redirect URI in the quizlet developer dashboard.

**Comment by ccwasden** [comment]
Perfect, thanks @maximbilan I figured it was something simple.

**Comment by maximbilan** [comment]
No problem:)
